# Generated by Django 2.2.4 on 2022-06-23 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0002_auto_20220623_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(to='app_one.Item'),
        ),
    ]
