# Generated by Django 2.2.4 on 2022-06-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_one', '0003_auto_20220623_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='items',
            field=models.ManyToManyField(related_name='users', to='app_one.Item'),
        ),
    ]
